### ISSUE TITLE
FIX Orchestra vs FIX Repository

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra-spec#11]
Chapter 2: "One conceptual metamodel governs all representations of FIX Orchestra and Repository knowledge bases.". Why do we use the term "Repository" in addition to Orchestra? Do we say that the FIX Repository is a(n) (integral) part of Orchestra or should it continue to exits in its own right?

**Comment by kleihan** [comment]
Just saw that chapter 3.1 defines the difference. "Repository 2016 Edition" is a name for an artefact and makes sense. But maybe we do not need the term "Repository" at all in the first paragraph of chapter 2 which is only about Orchestra, or?

**Comment by donmendelson** [comment]
@kleihan in early days before we came up with the Orchestra name, we were calling it "FIX Repository 2016 Edition". Orchestra remains the marketing name of the overall project. However, it contains two XML schemas, Repository schema (message structures and workflow) and the Interfaces schema (service offerings and sessions).  I'm open to renaming Repository if you like.

**Comment by kleihan** [comment]
So repository is part of Orchestra just like interfaces. Chapter 2 does not talk about schemas so that the sentence is less confusing for me if it says "One conceptual metamodel governs all representations of FIX Orchestra.". Or is that not enough?

**Comment by donmendelson** [comment]
Changing text to remove references to "Repository 2016 Edition" and clarify that there are two metamodels: repository and interfaces. Repository covers message models while interfaces covers service offerings and sessions.
