### ISSUE TITLE
Size of interface diagram

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra-spec#12]
Suggest to reduce size of interface diagram. It does not fit well on a single page and overwrites the footer. Resolution could be increased.

**Comment by donmendelson** [comment]
@kleihan I don't see support for image size in GitHub Flavored Markdown. Do you know how to do this? Perhaps with embedded HTML

**Comment by kleihan** [comment]
Yes, even if it is a workaround. Results are good enough and I have used it extensively for the online spec. It is a simple screen capture to a PNG file where you choose the width/height of the area to capture and adjust the original on the screen so that it fits into that box. What is the source of your diagram? Can you export it to PDF in a good quality and send to me? Then I can create a PNG.

**Comment by kleihan** [comment]
Interface diagram was split into two diagrams that can be put on separate pages by Pandoc.
