### ISSUE TITLE
Repository attributes - expressionLanguage

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra-spec#14]
Section 3.1.3.1 says "By default, the language for conditional expressions is the Score DSL. (See section below.) However, this may be overridden by setting a value to the attribute expressionLanguage."

Is "expressionLanguage" the actual name of an attribute? It occurs nowhere else in the spec. Should it be set e.g. in a different font to distinguish from normal text?

Issue extends to representation of attributes in general. At the moment they all look like normal text.

**Comment by donmendelson** [comment]
@kleihan expression language is an attribute

```xml
<xs:attribute name="expressionLanguage" type="xs:string" default="Score">
	<xs:annotation>
		<xs:documentation>The syntax of 'expressionType'</xs:documentation>
	</xs:annotation>
</xs:attribute>
```

**Comment by kleihan** [comment]
What is your view on using something else than normal text in markdown for attribute names? Same as `<datatype>`, i.e. `expressionLanguage`?

**Comment by donmendelson** [comment]
Will make sure that all attributes are in markdown format for literals.
