### ISSUE TITLE
Role of Extension Packs

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra-spec#15]
Section 3.2.2 Pedigree says "Each historical event is qualified by its protocol version and optionally, extension pack (EP), an interim publication between major versions."

This is no longer valid. FIX 5.0 SP2 is the last major version of FIX. EP are no longer interim, they are final and make up FIX Latest. The code snippet is missing the "addedEP" attribute (requires to change the chosen FIX element). Deprecation is a rare event in FIX and should not be used in an example unless it is to explain how deprecation looks like.

**Comment by donmendelson** [comment]
Wording will change to say FIX Latest. Add a more common example with "added" and "updated".
