### ISSUE TITLE
Document volumes vs business areas

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra-spec#16]
Section 3.3.2 says "The <sections> element tree names document volumes. Traditionally, they have been organized around pre-trade, trade, and post-trade information flows."

The FIX spec is no longer organized in volumes 1-7 and is now also available online, not only as documents. Suggest to replace "document volumes" to "business areas".

**Comment by donmendelson** [comment]
We have discussed the mapping of these terms to ISO 20022 in ISO TC68/SC9/WG1. 
FIX category = business area
FIX section = business process
