### ISSUE TITLE
Use cases for the presence attribute "forbidden"

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra-spec#18]
Why was this attribute introduced? The only example I can think of is CommissionData and CommissionDataGrp. The latter was introduced after the former due to the former being non-repeating. The fields of CommissionData are semantically forbidden to ever be added to the CommissionDataGrp but it seems rather artificial to add those fields with a "forbidden" presence attribue.

**Comment by donmendelson** [comment]
The documentation for forbidden is

> The field or component MUST NOT be present.

It is a way to say explicitly that a field or component is not supported and may result in rejection. For example, if a venue does not support Stop orders, it could mark StopPx as forbidden. 

With a rule, a field or component could be declared conditionally forbidden. (Usually we talk about conditionally required, but a rule can enforce any presence value.) For example, StopPx is forbidden for a certain asset class.

(Codes in a codeset can be marked with `supported="forbidden"` to show explicitly that they are not accepted.)

**Comment by kleihan** [comment]
Ok, I guess "forbidden" sounded quite harsh to me. The use case of "unsupported" overlaps with message structure lacking certain fields or defining a subset of a code set. Conditionally forbidden makes more sense and provides interesting use cases. If you have ever seen the Euronext spec which applies to multiple market places but limits the availability of features (e.g. order types) with color codes - it is a nightmare! By referencing a marketplace one could use "forbidden". But it still begs the questions why scenarios are not just as good.

**Comment by donmendelson** [comment]
@kleihan "forbidden" is intentionally harsh, meaning that if the element is sent, it may result in a rejection. Down the scale we have `presence="ignored"` that says the element is tolerated but not validated or used.

**Comment by donmendelson** [comment]
Suggestion:
The receiver of a message with a forbidden element or lacking a required element may reject it using appropriate actions defined by the rules of engagement.
