### ISSUE TITLE
Examples with non-standard FIX elements

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra-spec#19]
Section 3.8.2.4 contains a nested component OrderQtyDataCIV as part of the component OrderQtyData. The FIX standard does not have such a nested component in OrderQtyData. The last 3 fields of that component happen to be only for CIV.

Even if it is just an example I would prefer to only have 100% standard FIX in the Orchestra spec. The section 3.8.2.4 is also about mutually exclusive fields and not about nested components.

**Comment by donmendelson** [comment]
The example illustrates a new feature "oneOf", which wasn't expressed in the spec before.

It was based on discussion in this issue:
https://github.com/FIXTradingCommunity/fix-orchestra/issues/64
