### ISSUE TITLE
Deprecated attribute needs definition

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra-spec#2]
Elements in XML schema have attributes for pedigree (history of changes). The `deprecated` attribute needs more precise definition. How does it affect behavior? What is the difference between `supported` values forbidden or ignored and `deprecated`? Is an item ever removed after being deprecated?

**Comment by donmendelson** [comment]
Now it seems to me that handling of a deprecated element needs to be documented by the Orchestra file issuer rather than create a generic Orchestra versioning standard. If a deprecated item is replaced with a different encoding, then the new "concept" feature can be used to show equivalent old and new encodings.

**Comment by kleihan** [comment]
Added text to V1.1 RC1 to explain deprecation

**Comment by kleihan** [comment]
### Excerpt from Orchestra v1.1 RC1:

Deprecated elements are not removed from the repository. They may still be used based upon bilateral agreement. However, the publisher of the Orchestra XML file recommends to avoid its usage and should use the `replacedByField` attribute in case of a 1:1 change. The `<annotation>` element may additionally be used to describe the alternate element(s) and new approach.

**Example:** Code element that was deprecated

```xml
<fixr:code
  value="3" name="LocalCommission"
  added="FIX.4.0" deprecated="FIX.5.0SP2" deprecatedEP="204">
</fixr:code>
```
