### ISSUE TITLE
Underspecification of timer element

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra-spec#20]
Section 3.10.2.3 says "Some application layer and session layer behaviors are time dependent. An event can fire when a timer expires to affect other states or send a message.
Like a state machine, a <timer> is the child of an <actor>, and it has a name attribute."

This does not explain any attributes of timer and has no example.

**Comment by donmendelson** [comment]
Early in Orchestra development we tried to specify the session layer. A timeout would fire a TestRequest, for example. Probably better to use a trading example, perhaps ExecType=Expired fired at ExpireTime.
