### ISSUE TITLE
Case sensitivity of names

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra-spec#21]
Section 3.10.4.3 has an example:
<fixr:transitionRef actor="market" stateMachine="phase" name="resume"/>

The examples in sections 3.10.2.1 and 3.10.2.2 for an actor and a state machine have used uppercase names for Market and Phase. Is that ok, i.e. name are not case sensitive?

The name of the transition is also "Resumed" and not "Resume". A typo?

**Comment by donmendelson** [comment]
The XML schema allows any string for names. There are no constraints other than actor names must be unique. However, examples should follow a consistent style.

**Comment by kleihan** [comment]
Allowing any string does not really answer the question of case sensitivity. Are "market" and "Market" different or identical names in XML schema?

Does that mean it should be "resumed" with a "d"? Was your example connecting to the other examples for actors and state machines?

Most examples use lowercase in the spec, so I am fine to change the state machine example to lowercase names.

**Comment by donmendelson** [comment]
I want trying to be evasive. There is literally nothing in the schema currently that enforces matching of names in a state machine, so case sensitivity isn't relevant. However, I think that should change that by adding rules. We have such keys in the flow element to ensure that source and destination match actual actor names. 

By default, an XML processor would be case sensitive, but an Orchestra implemention could choose to be less strict about matching. Similarly, FIX engines often have switches to control how strictly the protocol is enforced.

**Comment by kleihan** [comment]
Ok, that makes sense. I will then adapt the example in 3.10.4.3 to match the names in previous sections, i.e. <fixr:transitionRef actor="Market" stateMachine="Phase" name="Resumed"/>. I think it would be good to avoid case sensitivity if we have that choice, just because of common sense. People should not use the same name twice with lowercase and uppercase versions. Whether they prefer to consistently use lowercase or uppercase should be up to the user for the names he is allowed to define. For names of FIX messages, components, groups, fields, codes it should be identical to FIXimate.
