### ISSUE TITLE
References to supplementary documentation

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra-spec#22]
The XML schema sections for both the repository and the interfaces refer to external html files (FixRepository.html, FixInterfaces.html). But it simply says "See the separate document...". Is it obvious where to find them or should we add a link?

**Comment by donmendelson** [comment]
See those files in the v1-0-RC5 folder. I will generate them (using XML Spy) for v1-0-DRAFT when all schema changes have finalized.
