### ISSUE TITLE
Time literals

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra-spec#23]
Section 5.1.2.5.2 says "A time literal is of FIX datatype UTCTimeOnly.". However, the format starts with a "T" which is only use for date-time literals in FIX (actually only FIXML). Why the "T" as prefix?

**Comment by donmendelson** [comment]
XML schema, including FIXML, uses ISO 8601 standard to format date and time literals.

**Comment by kleihan** [comment]
I cannot find the requirement to prefix time literals with a "T". On https://en.wikipedia.org/wiki/ISO_8601 they only show "T" as a separator if both date and time are present. Time literals are not shown with "T" as a prefix. What am I missing here?

**Comment by donmendelson** [comment]
I believe you're correct.

**Comment by kleihan** [comment]
Ok, I will adjust the examples in the spec accordingly

**Comment by donmendelson** [comment]
@kleihan I didn't realize that when you raised this issue that you were referring to a Score DSL expression. You are correct that ISO 8601 format only uses "T" to separate date from time portion of a date-time and does not use it for a stand-alone time. However, I used it in the DSL grammar to distinguish a time literal from date and duration literals. Durations are prefixed by "P" as in 8601.  (All are surrounded by "#" in the DSL.)

Here are some of my test cases for the DSL syntax:
      {"#2017-02-02T22:13:28Z#"},
      {"#2017-02-02T22:13:28.678Z#"},
      {"#T22:13:28Z#"},
      {"#2017-02-02#"},
      {"#2017-02-02T22:13:28-6:00#"},
      {"#P30D#"},
      {"#PT30S#"},

When I remove "T" from the time-only case, the parser fails. 

We have two choices
1. Accept the current time format for the DSL. It is slightly different from ISO 8601 in that is surrounded by "#" anyway to distinguish from other datatypes.
2. I can try to rework the DSL syntax to see if I can parse time without "T".

**Comment by donmendelson** [comment]
I think I can make it work without the extra "T". Will enter an issue for implementation change.

**Comment by donmendelson** [comment]
1.
