### ISSUE TITLE
Datatypes needs extensibility and mapping enhancements

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra-spec#33]
To specify rich datatypes in various use cases and encodings beyond FIX and tag-value requires extensibility. It would be common, particularly in binary encodings, to use a type with various ranges, for example long and short integers, unsigned integers, etc. in the same message schema. Currently, there is only FIX int type.

More broadly, the `datatype` element should be able to express types as described in ISO 11404 General Purpose Datatypes. That standard recognizes both primitive and derived datatypes.

Also, the `mappedDatatype` element, that has its origin in FIXML mapping, is inadequate for other encodings. In comparison, the SBE schema has a length attribute for encoding types but Orchestra does not. In SBE it is used to specify fixed-length encodings like country code of length 2.

**Comment by donmendelson** [comment]
The mappedDatatype element lacks a length attribute for fixed-length data structures, e.g. a fixed-length character array like country code versus a variable-length string.

**Comment by kleihan** [comment]
Duplicate to https://github.com/FIXTradingCommunity/fix-orchestra/issues/152?

**Comment by kleihan** [comment]
Confirmed as duplicate in Orchestra Repository Working Group meeting on Oct 26, 2023.
