### ISSUE TITLE
Define entity attribute "changeType" in spec

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra-spec#42]
Orchestra v1.0 spec does not explain this attribute, Schema shows the following:
```xml
	<xs:simpleType name="changeType_t">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Editorial"/>
			<xs:enumeration value="Definitional"/>
		</xs:restriction>
	</xs:simpleType>
```

**Comment by donmendelson** [comment]
This type was retained from FIX Unified Repository, but I'm not sure that anyone uses it.

**Comment by kleihan** [comment]
I am guessing it addresses the type of change made to an element. Editorial is only about annotation elements and anything else is definitional. I was unaware of it but actually like it. I sometimes see pedigree and wonder about what we changed and look into the EP to find out that it was just some typo that was corrected. Software can read this and decide to ignore it for code generation.
