### ISSUE TITLE
Update section on relevant DC terms

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra-spec#46]
Section 3.2.1 *Provenance* contains a subset of DC terms that are relevant in the context of electronic interfaces. The proposal is to update this section to make a clear recommendation of DC terms to be used and their semantics. This is linked to the existing issue https://github.com/FIXTradingCommunity/fix-orchestra/issues/186 about version attributes.

**Comment by kleihan** [comment]
See also #39 *Metadata usage guidelines*

**Comment by martinswanson** [comment]
As discussed at the previous Orchestra subcommittee meeting, here are our recommendations for the DC Terms. 

**Note**: In general, we favour a _permissive_ approach that avoids forcing users to specify lots of required fields, but being clear about the default behaviour if certain elements are not specified.

**1. Change the recommended elements for an Orchestra spec from [title, publisher, date issued, and rights] to [title, creator, created, conformsTo, and source].**
* **`title`**: Should be a required element. If missing, should default to using the repository name.
* **`creator`**: The recommended role should be `creator` not `publisher`, as not all specs are published (e.g. private specs)
* **`created`**: The recommended date should be `created` not `issued`, as not all specs reach issuance in their lifecycle
* **`conformsTo`**: Tools processing Orchestra files need to know which version of the technical spec the XML conforms to, hence `conformsTo` should be a recommended element. If missing, should default to the latest official version (currently Orchestra v1.0).
* **`source`**: URL to another Orchestra file. Should be a recommended element if a reference file was used to create the specification. This helps to preserve provenance, and allows validation across specifications e.g. if a scenario variant in a derived spec is valid with respect the reference specification.

**2. Additional elements recommended to support document generation (covers both PDF and EPUB formats)**
* `alternative` - Subtitle for the resource.
* `subject` - List of keywords used for search and categorisation.
* `abstract` - A summary of the resource.
* `issued` - If missing, default to created date.
* `dateAccepted` - if missing, default to issued date. If issued date is also missing, default to `created` date.
* `contributor` - Secondary author, in addition to the `creator`.
* `publisher` - Distributor of the Orchestra file or document. If missing, default to `creator`.

**3. Additional recommended elements**
* `rights` - optional, identifies the copyright holder _of the Orchestra file_
* `licence` - optional, URL to a licence file
* `isFormatOf` - URL to original resource that the Orchestra spec is based on (e.g. a PDF spec published by an Exchange).

We have confirmed that the above is sufficient to correctly set all the relevant metadata attributes for both PDF and EBUP documentation formats.
