### ISSUE TITLE
Change Section element to BusinessArea  for ISO 20022 alignment

### ISSUE THREAD

**Issue by jimnup** [FIXTradingCommunity/fix-orchestra-spec#6]
Propose renaming section level to business area for alignment with ISO 20022. The term section was not well thought through - it basically referred to one of the message volumes of the overall FIX Specification. The sections of Pre-trade, trade, post-trade, infrastructure are the current sections that map well to business areas.

**Comment by kleihan** [comment]
+1. Alex also used the term "Area" for his refactoring work.

**Comment by donmendelson** [comment]
A list of ISO 20022 Business Areas is [here](https://www.iso20022.org/sites/default/files/documents/general/ISO20022_BusinessAreas.pdf). Aside from changing the Orchestra XML element from `<section>` to `<businessArea>`, should we attempt to align the names?

**Comment by kleihan** [comment]
Difficult, ISO separates by asset class which FIX does not do. ISO is hence much more granular. We only have areas along the process chain. FIX messages are typically applicable to all asset classes. We could align ISO business areas with Orchestra message scenarios, e.g. identify the subset of a TCR that applies to trade reporting for a specific asset class. But that is a LOT of work...

Do we have the design option in Orchestra to create a scenario across multiple messages? For example, ISO has Foreign Exchange Trade (fxtr) with *Messages that support trade and post-trade processes for foreign exchange contracts, including order to buy or sell, execution, affirmation, confirmation, allocation and notification.* Aligning with FIX would require a meta-scenario that groups scenarios for specific FIX messages together. So, an Orchestra scenario called "ISOfxtr" would be a list of references to message level scenarios.

**Comment by donmendelson** [comment]
Currently, a scenario is defined at the level of a single message and its members. However, multiple messages could be associated by using a common scenario name. 

(There is no naming convention for scenarios yet. It is up to the Orchestra user.)

**Comment by donmendelson** [comment]
Removing hard-coded enumeration of section IDs. Allows traditional FIX business phases, or a different taxonomy can be used for non-FIX protocols.

**Comment by jimnup** [comment]
I put together a mapping of our sections to ISO 20022 businessAreas. It is not possible to map for ht reasons Hanno states. What is propsed instead is for us to use the term "Phase" as in face of the trading life cycle or business process and stay with our current values. What is proposed is to provide some form of tagging to tag our messages to ISO20022 businessAreas.

**Comment by donmendelson** [comment]
@jimnup for mapping a phase/facet/businessArea to another protocol like ISO 20022, we could take the approach that we did with datatypes. One FIX datatype can map to multiple protocols, such as JSON, SBE, XML, etc. In other words, a one-to-many relationship.

**Comment by jimnup** [comment]
Agree on the approach Don. And we don't want to restrict to hardcoding to ISO20022. That should be part of metadata as we will want to map concepts to other standards and other proprietary protocols.

**Comment by donmendelson** [comment]
The consensus as of June 5 is that we haven't come up with a better than "section". Revert to that name.
