### ISSUE TITLE
Schema lacks enum value for mapping to tag value encoding

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra-spec#8]
XML type datatypeStandard_enum is used for the "standard" attribute of element mappedDatatype. It has values for GPB, JSON, SBE, ISO 11404, and XML. However, it lacks a value for tag value encoding. I suggest "TagValue".

**Comment by kleihan** [comment]
I believe Jim introduced it already somewhere else as lowercase "tagvalue". I do not care but there should not be more than one.
